##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # rabbitmq
  rabbitmq:
    image: "${IMAGE_RABBITMQ}"
    container_name: "${CONTAINER_NAME}"
    hostname: "${CURRENT_NODE_HOSTNAME}"
    restart: "always"
    env_file:
      - ./rabbitmq.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/rabbitmq/data:/var/lib/rabbitmq:rw
    network_mode: "host"
    extra_hosts:
      - "${CLUSTER_NODE_HOSTNAME1}:${CLUSTER_NODE_ADDRESS1}"
      - "${CLUSTER_NODE_HOSTNAME2}:${CLUSTER_NODE_ADDRESS2}"
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
